### ISSUE TITLE
Update SLZ DA extension to support HA

### ISSUE THREAD

**Issue by ccmitchellusa** [terraform-ibm-modules/terraform-ibm-client-to-site-vpn#15]
### Description

Update the current SLZ DA extension at https://github.com/terraform-ibm-modules/terraform-ibm-client-to-site-vpn/tree/main/extensions/landing-zone to support HA. I think maybe we default it to HA by passing 2 subnets to the VPN, but customers will want the ability to choose which subnets to use, so need to provide the ability to do that as an override if we automatically assign 2 subnets by default.
NOTE: updates may be required to diagrams and ibm_catalog.json metadata

### New or affected modules
none

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aashiq-J** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-client-to-site-vpn/pull/93
